### ISSUE TITLE
Relax pinning of requirements

### ISSUE THREAD

**Issue by consideRatio** [jtpio/jupyterlab-system-monitor#93]
I'm tracking down why various packages are downgraded as part of installing other packages, and observed that this package on conda-forge (in alignment with requirements in setup.py) will downgrade `jupyter-resource-usage` to 0.5.x from its currently 0.6.x release.

I suspect this pinning was a precaution when it was introduced in https://github.com/jtpio/jupyterlab-system-monitor/pull/54, and that things may actually work. I'm not sure though.

If we could get more packages at 1.0.0 and beyond instead of staying at 0.X.Y we would be able to manage pins, but based on experience in the Python world it seems that the practice is that python packages are not putting a upper limit on what is supported as a precaution, but will do so if something is known to break.

**Comment by fperez** [comment]
Ping on this - I'm facing the same issue on one of my teaching hubs. Right now the solution seems to be to remove this one and rely strictly on `jupyter-resource-usage`, which is not ideal.

Any chance for an updated release that relaxes that constraint (after checking that it's in fact OK)? Thx!

**Comment by jtpio** [comment]
Looking at the diff in https://github.com/jtpio/jupyterlab-system-monitor/pull/54 the pin is set to `jupyter-resource-usage~=0.5` which should allow for install `jupyter-resource-usage==0.6.x`.

Also checked this is still the case on the main branch: 

https://github.com/jtpio/jupyterlab-system-monitor/blob/eb3d0aace569184034bc29215067dfb3a5f73fcc/setup.py#L71

This looks like an issue with the conda recipe though which has `jupyter-resource-usage >=0.5.0,<0.6.0` at the moment: https://github.com/conda-forge/jupyterlab-system-monitor-feedstock/blob/402399196eb2cacc1107e972da63e7a39207237e/recipe/meta.yaml#L26. I'll open a PR there to relax the dependency since it should also work with 0.6.

**Comment by jtpio** [comment]
Opened https://github.com/conda-forge/jupyterlab-system-monitor-feedstock/pull/3

**Comment by jtpio** [comment]
Closing as fixed by https://github.com/conda-forge/jupyterlab-system-monitor-feedstock/pull/3.
